/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductoresRouteImport } from './routes/productores'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as MercadoMixtoRouteImport } from './routes/mercado-mixto'
import { Route as MercadoAgricolaRouteImport } from './routes/mercado-agricola'
import { Route as FoodMarketRouteImport } from './routes/food-market'
import { Route as FleaMarketRouteImport } from './routes/flea-market'
import { Route as FeriaArtesanalRouteImport } from './routes/feria-artesanal'
import { Route as EnviarRouteImport } from './routes/enviar'
import { Route as BazarPopUpRouteImport } from './routes/bazar-pop-up'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmprendedoresIndexRouteImport } from './routes/emprendedores.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminSubmissionsRouteImport } from './routes/_admin/admin.submissions'
import { Route as AdminAdminProducersRouteImport } from './routes/_admin/admin.producers'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin/admin.messages'
import { Route as AdminAdminMarketsRouteImport } from './routes/_admin/admin.markets'
import { Route as AdminAdminEmprendedoresRouteImport } from './routes/_admin/admin.emprendedores'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoresRoute = ProductoresRouteImport.update({
  id: '/productores',
  path: '/productores',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoMixtoRoute = MercadoMixtoRouteImport.update({
  id: '/mercado-mixto',
  path: '/mercado-mixto',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoAgricolaRoute = MercadoAgricolaRouteImport.update({
  id: '/mercado-agricola',
  path: '/mercado-agricola',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodMarketRoute = FoodMarketRouteImport.update({
  id: '/food-market',
  path: '/food-market',
  getParentRoute: () => rootRouteImport,
} as any)
const FleaMarketRoute = FleaMarketRouteImport.update({
  id: '/flea-market',
  path: '/flea-market',
  getParentRoute: () => rootRouteImport,
} as any)
const FeriaArtesanalRoute = FeriaArtesanalRouteImport.update({
  id: '/feria-artesanal',
  path: '/feria-artesanal',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarRoute = EnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarPopUpRoute = BazarPopUpRouteImport.update({
  id: '/bazar-pop-up',
  path: '/bazar-pop-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprendedoresIndexRoute = EmprendedoresIndexRouteImport.update({
  id: '/emprendedores/',
  path: '/emprendedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSubmissionsRoute = AdminAdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProducersRoute = AdminAdminProducersRouteImport.update({
  id: '/admin/producers',
  path: '/admin/producers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMarketsRoute = AdminAdminMarketsRouteImport.update({
  id: '/admin/markets',
  path: '/admin/markets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmprendedoresRoute = AdminAdminEmprendedoresRouteImport.update({
  id: '/admin/emprendedores',
  path: '/admin/emprendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bazar-pop-up': typeof BazarPopUpRoute
  '/enviar': typeof EnviarRoute
  '/feria-artesanal': typeof FeriaArtesanalRoute
  '/flea-market': typeof FleaMarketRoute
  '/food-market': typeof FoodMarketRoute
  '/mercado-agricola': typeof MercadoAgricolaRoute
  '/mercado-mixto': typeof MercadoMixtoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/productores': typeof ProductoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/emprendedores/': typeof EmprendedoresIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/emprendedores': typeof AdminAdminEmprendedoresRoute
  '/admin/markets': typeof AdminAdminMarketsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/producers': typeof AdminAdminProducersRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bazar-pop-up': typeof BazarPopUpRoute
  '/enviar': typeof EnviarRoute
  '/feria-artesanal': typeof FeriaArtesanalRoute
  '/flea-market': typeof FleaMarketRoute
  '/food-market': typeof FoodMarketRoute
  '/mercado-agricola': typeof MercadoAgricolaRoute
  '/mercado-mixto': typeof MercadoMixtoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/productores': typeof ProductoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/emprendedores': typeof EmprendedoresIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/emprendedores': typeof AdminAdminEmprendedoresRoute
  '/admin/markets': typeof AdminAdminMarketsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/producers': typeof AdminAdminProducersRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/bazar-pop-up': typeof BazarPopUpRoute
  '/enviar': typeof EnviarRoute
  '/feria-artesanal': typeof FeriaArtesanalRoute
  '/flea-market': typeof FleaMarketRoute
  '/food-market': typeof FoodMarketRoute
  '/mercado-agricola': typeof MercadoAgricolaRoute
  '/mercado-mixto': typeof MercadoMixtoRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/productores': typeof ProductoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/emprendedores/': typeof EmprendedoresIndexRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/emprendedores': typeof AdminAdminEmprendedoresRoute
  '/_admin/admin/markets': typeof AdminAdminMarketsRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/producers': typeof AdminAdminProducersRoute
  '/_admin/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bazar-pop-up'
    | '/enviar'
    | '/feria-artesanal'
    | '/flea-market'
    | '/food-market'
    | '/mercado-agricola'
    | '/mercado-mixto'
    | '/politica-de-privacidad'
    | '/productores'
    | '/sitemap.xml'
    | '/admin/login'
    | '/emprendedores/'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/emprendedores'
    | '/admin/markets'
    | '/admin/messages'
    | '/admin/producers'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bazar-pop-up'
    | '/enviar'
    | '/feria-artesanal'
    | '/flea-market'
    | '/food-market'
    | '/mercado-agricola'
    | '/mercado-mixto'
    | '/politica-de-privacidad'
    | '/productores'
    | '/sitemap.xml'
    | '/admin/login'
    | '/emprendedores'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/emprendedores'
    | '/admin/markets'
    | '/admin/messages'
    | '/admin/producers'
    | '/admin/submissions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/bazar-pop-up'
    | '/enviar'
    | '/feria-artesanal'
    | '/flea-market'
    | '/food-market'
    | '/mercado-agricola'
    | '/mercado-mixto'
    | '/politica-de-privacidad'
    | '/productores'
    | '/sitemap.xml'
    | '/admin/login'
    | '/emprendedores/'
    | '/_admin/admin/analytics'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/emprendedores'
    | '/_admin/admin/markets'
    | '/_admin/admin/messages'
    | '/_admin/admin/producers'
    | '/_admin/admin/submissions'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BazarPopUpRoute: typeof BazarPopUpRoute
  EnviarRoute: typeof EnviarRoute
  FeriaArtesanalRoute: typeof FeriaArtesanalRoute
  FleaMarketRoute: typeof FleaMarketRoute
  FoodMarketRoute: typeof FoodMarketRoute
  MercadoAgricolaRoute: typeof MercadoAgricolaRoute
  MercadoMixtoRoute: typeof MercadoMixtoRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  ProductoresRoute: typeof ProductoresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmprendedoresIndexRoute: typeof EmprendedoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productores': {
      id: '/productores'
      path: '/productores'
      fullPath: '/productores'
      preLoaderRoute: typeof ProductoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-mixto': {
      id: '/mercado-mixto'
      path: '/mercado-mixto'
      fullPath: '/mercado-mixto'
      preLoaderRoute: typeof MercadoMixtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-agricola': {
      id: '/mercado-agricola'
      path: '/mercado-agricola'
      fullPath: '/mercado-agricola'
      preLoaderRoute: typeof MercadoAgricolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-market': {
      id: '/food-market'
      path: '/food-market'
      fullPath: '/food-market'
      preLoaderRoute: typeof FoodMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flea-market': {
      id: '/flea-market'
      path: '/flea-market'
      fullPath: '/flea-market'
      preLoaderRoute: typeof FleaMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feria-artesanal': {
      id: '/feria-artesanal'
      path: '/feria-artesanal'
      fullPath: '/feria-artesanal'
      preLoaderRoute: typeof FeriaArtesanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar': {
      id: '/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof EnviarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar-pop-up': {
      id: '/bazar-pop-up'
      path: '/bazar-pop-up'
      fullPath: '/bazar-pop-up'
      preLoaderRoute: typeof BazarPopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprendedores/': {
      id: '/emprendedores/'
      path: '/emprendedores'
      fullPath: '/emprendedores/'
      preLoaderRoute: typeof EmprendedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/submissions': {
      id: '/_admin/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminAdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/producers': {
      id: '/_admin/admin/producers'
      path: '/admin/producers'
      fullPath: '/admin/producers'
      preLoaderRoute: typeof AdminAdminProducersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/markets': {
      id: '/_admin/admin/markets'
      path: '/admin/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminAdminMarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/emprendedores': {
      id: '/_admin/admin/emprendedores'
      path: '/admin/emprendedores'
      fullPath: '/admin/emprendedores'
      preLoaderRoute: typeof AdminAdminEmprendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminEmprendedoresRoute: typeof AdminAdminEmprendedoresRoute
  AdminAdminMarketsRoute: typeof AdminAdminMarketsRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminProducersRoute: typeof AdminAdminProducersRoute
  AdminAdminSubmissionsRoute: typeof AdminAdminSubmissionsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminEmprendedoresRoute: AdminAdminEmprendedoresRoute,
  AdminAdminMarketsRoute: AdminAdminMarketsRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminProducersRoute: AdminAdminProducersRoute,
  AdminAdminSubmissionsRoute: AdminAdminSubmissionsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BazarPopUpRoute: BazarPopUpRoute,
  EnviarRoute: EnviarRoute,
  FeriaArtesanalRoute: FeriaArtesanalRoute,
  FleaMarketRoute: FleaMarketRoute,
  FoodMarketRoute: FoodMarketRoute,
  MercadoAgricolaRoute: MercadoAgricolaRoute,
  MercadoMixtoRoute: MercadoMixtoRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  ProductoresRoute: ProductoresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmprendedoresIndexRoute: EmprendedoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
